'use client';

import { useMemo, useState } from 'react';
import { BookOpen, CalendarDays, Check, ChevronRight, CircleUserRound, Film, Flower2, Headphones, HeartHandshake, Image as ImageIcon, LetterText, MessageCircleMore, Mic2, Play, Quote, Sparkles, Users } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { collections, people, type Person } from '@/lib/family-data';

export default function Home() {
  const defaultPersonId = people.find((person) => person.featured)?.id ?? people[0]?.id ?? '';
  const [selected, setSelected] = useState(defaultPersonId);
  const active = useMemo(() => people.find((person) => person.id === selected) ?? people[0], [selected]);

  const selectPerson = (id: string) => {
    setSelected(id);
    window.setTimeout(() => document.getElementById('profile')?.scrollIntoView({ behavior: 'smooth', block: 'start' }), 80);
  };

  return (
    <main className="min-h-screen overflow-hidden bg-background text-foreground">
      <header className="sticky top-0 z-40 border-b border-[#d9cebb]/75 bg-[#f8f3e8]/94 backdrop-blur-xl">
        <div className="mx-auto flex h-20 max-w-[1440px] items-center justify-between px-5 md:px-10">
          <a href="#family" className="flex items-center gap-3" aria-label="Everroot home"><span className="grid size-10 place-items-center rounded-full bg-[#a34f42] text-[#fffaf0]"><Flower2 size={20} strokeWidth={1.7} /></span><div><p className="font-serif text-xl font-semibold tracking-[.08em] text-[#392f28]">Everroot</p><p className="text-[10px] uppercase tracking-[.24em] text-[#8b7563]">Companionship becomes legacy</p></div></a>
          <nav className="hidden items-center gap-6 text-sm text-[#6f6256] lg:flex" aria-label="Main navigation"><a href="#family">Family</a><a href="#profile">Life record</a><a href="#story">Story</a><a href="#film">Film</a><a href="#letter">Letter</a><a href="#voice">Voice</a></nav>
          <span className="rounded-full border border-[#b8aa94] bg-white/40 px-3 py-1.5 text-xs text-[#796956]">Private family space</span>
        </div>
      </header>

      <section id="family" className="paper-texture border-b border-[#d8cbb8] py-16 md:py-20">
        <div className="mx-auto grid max-w-7xl gap-12 px-6 lg:grid-cols-[.72fr_1.28fr]">
          <div className="lg:sticky lg:top-28 lg:self-start"><p className="eyebrow"><Users size={14} /> The Zhao · Lin family</p><h1 className="font-serif text-5xl leading-[1.06] tracking-[-.025em] text-[#332b25] md:text-6xl">One family.<br /><em className="font-normal text-[#9c4b40]">Many witnesses.</em></h1><p className="mt-6 max-w-md leading-7 text-[#726458]">Every person is remembered from more than one direction. Their own words sit beside the memories of parents, partners, children and grandchildren.</p><div className="mt-8 flex items-start gap-3 rounded-2xl border border-[#d8c7ad] bg-[#fffaf0]/70 p-4 text-sm leading-6 text-[#67594e]"><HeartHandshake className="mt-1 shrink-0 text-[#9c4b40]" size={18} /><p><strong className="font-semibold text-[#44382f]">Always someone to talk to.</strong><br />Ordinary evenings become a place to feel heard, remember and stay close to family.</p></div></div>
          <div className="rounded-[32px] border border-[#d6c6ae] bg-[#fffaf0]/80 p-6 shadow-[0_24px_80px_rgba(92,66,42,.09)] md:p-10"><div className="mb-8 flex flex-wrap items-end justify-between gap-4"><div><p className="font-serif text-2xl text-[#3d332b]">Three generations</p><p className="mt-1 text-xs tracking-wide text-[#8a796a]">Select a person to open their complete archive</p></div><span className="rounded-full bg-[#e7eee8] px-3 py-1.5 text-[11px] font-semibold uppercase tracking-[.14em] text-[#51655b]">{people.length} profiles · 27 memories</span></div><div className="tree-grid" aria-label="Interactive family tree"><div className="tree-couple">{people.slice(0, 2).map((person) => <PersonNode key={person.id} person={person} selected={selected === person.id} onSelect={selectPerson} />)}</div><div className="tree-line line-one" />{people[2] && <div className="tree-child"><PersonNode person={people[2]} selected={selected === people[2].id} onSelect={selectPerson} /></div>}<div className="tree-line" />{people[3] && <div className="tree-grandchild"><PersonNode person={people[3]} selected={selected === people[3].id} onSelect={selectPerson} /></div>}</div>{people.length > 4 && <div className="mt-6 grid gap-3 border-t border-[#ded0bd] pt-6 sm:grid-cols-2">{people.slice(4).map((person) => <PersonNode key={person.id} person={person} selected={selected === person.id} onSelect={selectPerson} />)}</div>}<div className="mt-8 border-t border-[#ded0bd] pt-6"><p className="mb-3 text-[10px] font-semibold uppercase tracking-[.2em] text-[#957c67]">Memory sources in this family</p><div className="flex flex-wrap gap-2 text-xs text-[#65584d]"><SourcePill icon={MessageCircleMore} text="11 companion conversations" /><SourcePill icon={Mic2} text="7 voice notes" /><SourcePill icon={ImageIcon} text="9 reviewed photographs" /></div></div></div>
        </div>
      </section>

      <section id="profile" className="scroll-mt-20 bg-[#eee4d5] py-20 md:py-28"><div className="mx-auto max-w-7xl px-6">
        <div className="profile-header grid overflow-hidden rounded-[34px] border border-white/60 bg-[#fbf6ec] shadow-[0_28px_90px_rgba(75,53,37,.13)] lg:grid-cols-[320px_1fr]"><div className="relative min-h-[330px] bg-[#d8c9b4]">{active.avatar ? <img src={active.avatar} alt={`Portrait of ${active.name}`} className="absolute inset-0 size-full object-cover" /> : <div className="absolute inset-0 grid place-items-center bg-[radial-gradient(circle_at_50%_35%,#f2e9da,transparent_30%),linear-gradient(150deg,#d8cab7,#aa9780)]"><CircleUserRound size={112} strokeWidth={1} className="text-white/80" /></div>}<div className="absolute inset-x-0 bottom-0 bg-gradient-to-t from-[#2d2824]/75 to-transparent p-6 pt-20 text-white"><span className="rounded-full border border-white/30 bg-black/15 px-3 py-1 text-[10px] font-semibold uppercase tracking-[.16em]">{active.status}</span></div></div><div className="p-7 md:p-11"><div className="flex flex-wrap items-start justify-between gap-6"><div><p className="text-xs font-semibold uppercase tracking-[.2em] text-[#9b4b40]">Family portrait</p><h2 className="mt-3 font-serif text-5xl text-[#392f28]">{active.name}</h2><p className="mt-2 font-serif text-2xl text-[#8c5a4b]">{active.chinese} · {active.years}</p></div><div className="rounded-2xl border border-[#d8c8b2] bg-[#f5ecdd] px-4 py-3 text-right"><p className="text-[10px] uppercase tracking-[.17em] text-[#927d69]">Family role</p><p className="mt-1 text-sm font-medium text-[#52453a]">{active.role}</p></div></div><p className="mt-7 max-w-3xl text-base leading-8 text-[#65574c]">{active.overview}</p><div className="mt-8 grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><Info label="Relationship" value={active.relation} /><Info label="Home" value={active.location} /><Info label="Occupation" value={active.occupation} /><Info label="Personality" value={active.personality} /></div></div></div>
        <div className="mt-8 grid gap-8 lg:grid-cols-[.85fr_1.15fr]"><aside className="space-y-8"><section className="archive-card"><SectionLabel icon={Sparkles} text="Personal details" /><h3 className="font-serif text-2xl text-[#42362e]">The texture of an ordinary life</h3><p className="mt-3 text-xs leading-5 text-[#8a796b]">Specific details are retained because personality often lives in habits rather than summaries.</p><h4 className="detail-heading">Interests</h4><div className="flex flex-wrap gap-2">{active.interests.map((item) => <span key={item} className="detail-chip">{item}</span>)}</div><h4 className="detail-heading">Small things the family remembers</h4><ul className="space-y-3">{active.smallThings.map((item) => <li key={item} className="flex gap-3 text-sm leading-6 text-[#65574c]"><span className="mt-2 size-1.5 shrink-0 rounded-full bg-[#a25346]" />{item}</li>)}</ul><p className="mt-6 border-t border-[#ded0bd] pt-5 text-xs italic leading-5 text-[#8a7868]">{active.personalityNote}</p></section><section className="archive-card"><SectionLabel icon={Users} text="Family perspectives" /><h3 className="font-serif text-2xl text-[#42362e]">No life has one narrator</h3><div className="mt-6 space-y-5">{active.perspectives.map((view) => <article key={view.speaker} className="perspective"><div className="flex items-baseline justify-between gap-4"><h4 className="font-serif text-lg text-[#493c33]">{view.speaker}</h4><span className="text-[10px] uppercase tracking-[.14em] text-[#9a7d68]">{view.relationship}</span></div><p className="mt-3 text-sm leading-6 text-[#65574c]">“{view.text}”</p><p className="mt-3 text-[10px] tracking-wide text-[#a08c7a]">{view.source}</p></article>)}</div></section></aside>
          <section className="archive-card"><SectionLabel icon={CalendarDays} text="Life record" /><div className="flex flex-wrap items-end justify-between gap-4"><div><h3 className="font-serif text-3xl text-[#42362e]">Life and timeline</h3><p className="mt-2 max-w-lg text-sm leading-6 text-[#79695d]">The places, dates and turning points this family wants to remember, with uncertain details left honestly open.</p></div><span className="inline-flex items-center gap-2 rounded-full bg-[#e7eee8] px-3 py-1.5 text-xs text-[#567063]"><Check size={13} /> Kept by the family</span></div><div className="mt-10 space-y-0">{active.timeline.map((item) => <div key={`${active.id}-${item.year}`} className="timeline-item"><div className="timeline-dot" /><div className="pb-10"><div className="mb-2 flex flex-wrap items-center gap-3"><span className="font-serif text-xl text-[#9a4c41]">{item.year}</span><span className="text-[10px] uppercase tracking-[.17em] text-[#9a8877]">{item.place}</span></div><h4 className="font-serif text-xl text-[#45382f]">{item.title}</h4><p className="mt-2 max-w-2xl text-sm leading-7 text-[#79695d]">{item.copy}</p></div></div>)}</div><div className="mt-2 rounded-2xl border-l-2 border-[#a95a4d] bg-[#f6ecdf] p-6"><Quote size={20} className="text-[#a95a4d]" /><p className="mt-3 font-serif text-2xl leading-9 text-[#5a463a]">“{active.quote}”</p><p className="mt-3 text-[10px] uppercase tracking-[.17em] text-[#9a8270]">In their own words</p></div></section></div>
      </div></section>

      <section id="story" className="paper-texture py-24 md:py-32"><div className="mx-auto max-w-5xl px-6"><div className="mb-14 grid gap-8 md:grid-cols-[.8fr_1.2fr] md:items-end"><div><p className="eyebrow"><BookOpen size={14} /> Complete story</p><h2 className="font-serif text-5xl leading-tight text-[#352c26] md:text-6xl">{active.storyTitle}</h2></div><p className="border-l border-[#c7b59d] pl-7 font-serif text-2xl leading-9 text-[#6a5142]">{active.storyDeck}</p></div><article className="story-manuscript"><p className="mb-8 text-xs font-semibold uppercase tracking-[.22em] text-[#8f493f]">Remembered in {active.perspectives.length} voices</p>{active.story.map((paragraph, index) => <p key={`${active.id}-story-${index}`} className={index === 0 ? 'dropcap' : ''}>{paragraph}</p>)}</article></div></section>

      <section id="film" className="bg-[#33483f] py-24 text-[#f8f0df] md:py-28">
        <div className="mx-auto grid max-w-6xl items-center gap-12 px-6 lg:grid-cols-[1.08fr_.92fr]">
          <MemoryFilm person={active} />
          <div><p className="mb-5 flex items-center gap-2 text-xs font-semibold uppercase tracking-[.23em] text-[#d9a27e]"><Film size={14} /> Life film</p><h2 className="font-serif text-4xl leading-tight md:text-5xl">{active.film ? <>A life told<br />in one minute.</> : <>A life, remembered<br />in motion.</>}</h2><p className="mt-6 max-w-lg text-base leading-7 text-[#d8d1c3]">{active.film?.description ?? `No life film has been added to ${active.name}’s family page yet. Their written story, timeline and family perspectives remain available above.`}</p><div className="mt-8 grid grid-cols-2 gap-3 text-xs text-[#d2c8b8]"><MediaStat label="Duration" value={active.film?.duration ?? '—'} /><MediaStat label="Chapters" value={active.film?.chapters ?? '—'} /><MediaStat label="Language" value={active.film?.language ?? '—'} /><MediaStat label="Status" value={active.film ? 'Ready to watch' : 'No film yet'} /></div></div>
        </div>
      </section>

      <section id="letter" className="relative overflow-hidden bg-[#e8ddca] py-24 md:py-32"><div className="absolute inset-0 opacity-40 [background:radial-gradient(circle_at_20%_10%,#fff9e9,transparent_35%)]" /><div className="relative mx-auto grid max-w-6xl items-center gap-14 px-6 lg:grid-cols-[.68fr_1.32fr]"><div><p className="eyebrow"><LetterText size={14} /> A letter across generations</p><h2 className="font-serif text-4xl leading-tight text-[#3d3027] md:text-5xl">What a life<br />wants to pass on.</h2><p className="mt-6 max-w-sm text-base leading-7 text-[#756457]">A family letter holds more than events. It carries the meaning one generation hopes the next will recognise in ordinary objects, repeated habits and acts of care.</p><div className="mt-8 inline-flex items-center gap-2 rounded-full border border-[#bfa990] bg-[#f7efdf]/70 px-4 py-2 text-xs text-[#765f50]"><Check size={14} className="text-[#697c68]" /> Kept in {active.name}’s archive</div></div><article className="letter-paper rotate-[.25deg] p-9 md:p-14"><p className="mb-10 text-sm text-[#8b6d58]">Dear {active.letterTo},</p><div className="space-y-6 font-serif text-lg leading-8 text-[#514238]">{active.letter.map((paragraph, index) => <p key={`${active.id}-letter-${index}`}>{paragraph}</p>)}</div><div className="mt-10 flex items-end justify-between"><div><p className="font-serif text-lg text-[#514238]">With love,</p><p className="mt-2 font-serif text-2xl text-[#974b40]">{active.name} · {active.chinese}</p></div><span className="seal">{active.chinese.slice(0, 1)}</span></div></article></div></section>

      <section id="voice" className="paper-texture py-24 md:py-28"><div className="mx-auto max-w-6xl px-6"><div className="grid gap-10 rounded-[32px] border border-[#d4c4ad] bg-[#fffaf0]/80 p-7 shadow-[0_24px_70px_rgba(84,61,43,.08)] md:p-12 lg:grid-cols-[.82fr_1.18fr]"><div><p className="eyebrow"><Headphones size={14} /> Voice archive</p><h2 className="font-serif text-4xl leading-tight text-[#392f28]">A letter can still<br />sound like home.</h2><p className="mt-5 max-w-md leading-7 text-[#726458]">Listen when reading is not enough. Each recording stays beside its letter, language and written transcript so the whole family can return to it.</p></div><div className="rounded-[26px] bg-[#3b4e45] p-6 text-[#f8f0df] md:p-8"><div><p className="text-[10px] uppercase tracking-[.2em] text-[#d7a583]">{active.voice.label}</p><h3 className="mt-2 font-serif text-2xl">{active.voice.language}</h3><p className="mt-2 max-w-xl text-sm leading-6 text-white/65">{active.voice.note}</p></div>{active.voice.src ? <><audio key={active.id} className="archive-audio mt-8 w-full" controls preload="metadata"><source src={active.voice.src} type="audio/mpeg" />Your browser does not support embedded audio.</audio><div className="mt-5 flex flex-wrap gap-2"><span className="audio-pill">{active.voice.duration}</span><span className="audio-pill">Transcript included</span><span className="audio-pill">Mandarin reading</span></div>{active.voice.transcript && <details className="mt-6 rounded-2xl border border-white/15 bg-black/10 p-4"><summary className="cursor-pointer text-sm text-[#f4e6d0]">Read the Chinese transcript</summary><p lang="zh-CN" className="mt-4 text-sm leading-7 text-white/70">{active.voice.transcript}</p></details>}</> : <div className="mt-8 rounded-2xl border border-white/15 bg-black/10 p-5 text-sm leading-6 text-white/65">This person’s family-letter reading has not been added yet.</div>}</div></div>
        <div className="mt-20"><div className="mx-auto max-w-2xl text-center"><p className="justify-center eyebrow"><Sparkles size={14} /> Inside this family archive</p><h2 className="font-serif text-4xl text-[#392e27] md:text-5xl">A family kept in more than names and dates.</h2></div><div className="mt-12 grid gap-5 md:grid-cols-2 lg:grid-cols-4">{collections.map((item) => <article key={item.title} className="process-card"><p className="font-serif text-4xl text-[#9c4b40]">{item.count}</p><h3 className="mt-6 font-serif text-xl text-[#43362e]">{item.title}</h3><p className="mt-3 text-sm leading-6 text-[#7b6b5f]">{item.copy}</p></article>)}</div></div></div></section>
      <footer className="border-t border-[#cfc0aa] bg-[#f3ecde] py-10"><div className="mx-auto flex max-w-6xl flex-col items-center justify-between gap-5 px-6 text-center sm:flex-row sm:text-left"><div className="flex items-center gap-3"><span className="grid size-9 place-items-center rounded-full bg-[#a34f42] text-white"><Flower2 size={17} /></span><div><p className="font-serif text-lg">Everroot</p><p className="text-[10px] uppercase tracking-[.2em] text-[#8d7967]">Companionship · Continuity</p></div></div><p className="text-xs leading-5 text-[#8a7766]">The Zhao · Lin family archive<br />Private memories, shared with care.</p></div></footer>
    </main>
  );
}

function PersonNode({ person, selected, onSelect }: { person: Person; selected: boolean; onSelect: (id: string) => void }) { return <Button type="button" variant="ghost" onClick={() => onSelect(person.id)} className={`person-node h-auto justify-start whitespace-normal ${selected ? 'is-selected' : ''}`} aria-pressed={selected}><span className="avatar-ring overflow-hidden" style={{ '--avatar-color': person.color } as React.CSSProperties}>{person.avatar ? <img src={person.avatar} alt="" className="size-full object-cover" /> : <span>{person.chinese.slice(-1)}</span>}</span><span className="min-w-0 flex-1 text-left"><span className="block truncate font-serif text-[15px] text-[#3c322b]">{person.name}</span><span className="block text-[10px] uppercase tracking-[.12em] text-[#927d6c]">{person.years} · {person.status}</span></span><ChevronRight size={14} className="text-[#a48d78]" /></Button>; }
function MemoryFilm({ person }: { person: Person }) {
  if (person.film) return <div className="relative aspect-video overflow-hidden rounded-[28px] border border-white/15 bg-[#21342d] shadow-[0_30px_80px_rgba(20,27,24,.3)]"><video className="size-full object-cover" controls preload="metadata" poster={person.film.poster}><source src={person.film.src} type="video/mp4" />{person.film.captions && <track kind="subtitles" src={person.film.captions} srcLang="en" label="English" default />}Your browser does not support embedded video.</video><span className="pointer-events-none absolute left-5 top-5 rounded-full border border-white/25 bg-black/40 px-3 py-1 text-[10px] uppercase tracking-[.2em]">Life film · {person.film.duration}</span></div>;
  return <div className="video-frame relative aspect-video overflow-hidden rounded-[28px] border border-white/15 shadow-[0_30px_80px_rgba(20,27,24,.3)]"><div className="absolute inset-0 bg-gradient-to-t from-[#17241f]/90 via-[#17241f]/25 to-black/10" /><div className="absolute inset-0 grid place-items-center"><span className="grid size-16 place-items-center rounded-full border border-white/30 bg-[#f4e9d3] text-[#8f483d]"><Play className="ml-1" size={24} /></span></div><div className="absolute bottom-6 left-7"><p className="font-serif text-2xl">{person.storyTitle}</p><p className="mt-2 text-xs uppercase tracking-[.16em] text-white/60">No life film added yet</p></div></div>;
}
function SourcePill({ icon: Icon, text }: { icon: typeof Mic2; text: string }) { return <span className="inline-flex items-center gap-2 rounded-full border border-[#d8c9b4] bg-white/50 px-3 py-2"><Icon size={13} className="text-[#9b5549]" />{text}</span>; }
function Info({ label, value }: { label: string; value: string }) { return <div className="rounded-xl border border-[#ded0bd] bg-[#fffaf0]/70 p-4"><p className="text-[9px] font-semibold uppercase tracking-[.17em] text-[#9a816d]">{label}</p><p className="mt-2 text-sm leading-5 text-[#50443a]">{value}</p></div>; }
function SectionLabel({ icon: Icon, text }: { icon: typeof Sparkles; text: string }) { return <p className="eyebrow"><Icon size={14} />{text}</p>; }
function MediaStat({ label, value }: { label: string; value: string }) { return <div className="rounded-xl border border-white/15 bg-black/10 p-3"><p className="text-[9px] uppercase tracking-[.17em] text-white/50">{label}</p><p className="mt-1.5 text-sm text-[#f4ead9]">{value}</p></div>; }
